#ifndef LV_CONF_H
#define LV_CONF_H

#define LV_COLOR_DEPTH 16

#define LV_USE_MEM_MONITOR 0
#define LV_USE_LOG 0
#define LV_USE_GPU 0
#define LV_USE_USER_DATA 0

#define LV_FONT_MONTSERRAT_8 1
#define LV_FONT_MONTSERRAT_10 1
#define LV_FONT_MONTSERRAT_12 1
#define LV_FONT_MONTSERRAT_14 1
#define LV_FONT_MONTSERRAT_16 1
#define LV_FONT_MONTSERRAT_18 0
#define LV_FONT_MONTSERRAT_20 1
#define LV_FONT_MONTSERRAT_22 0
#define LV_FONT_MONTSERRAT_24 1
#define LV_FONT_MONTSERRAT_26 0
#define LV_FONT_MONTSERRAT_28 0
#define LV_FONT_MONTSERRAT_30 0
#define LV_FONT_MONTSERRAT_32 0
#define LV_FONT_MONTSERRAT_34 0
#define LV_FONT_MONTSERRAT_36 0
#define LV_FONT_MONTSERRAT_38 0
#define LV_FONT_MONTSERRAT_40 0
#define LV_FONT_MONTSERRAT_42 0
#define LV_FONT_MONTSERRAT_44 0
#define LV_FONT_MONTSERRAT_46 0
#define LV_FONT_MONTSERRAT_48 0

#define LV_USE_ANIMATION 1
#define LV_ANIMATION_MAX_RUNNING 16

#define LV_USE_BTN 1
#define LV_USE_LABEL 1
#define LV_USE_BAR 1
#define LV_USE_LIST 1
#define LV_USE_ROLLER 0
#define LV_USE_SLIDER 0
#define LV_USE_SWITCH 0
#define LV_USE_CHECKBOX 0
#define LV_USE_DROP_DOWN 0
#define LV_USE_TEXTAREA 0
#define LV_USE_TABLE 0
#define LV_USE_TABVIEW 0
#define LV_USE_WIN 0
#define LV_USE_CHART 0
#define LV_USE_MENU 0
#define LV_USE_CALENDAR 0
#define LV_USE_IMAGE 1
#define LV_USE_LINE 1
#define LV_USE_ARC 0
#define LV_USE_SPINBOX 0
#define LV_USE_SPINNER 0
#define LV_USE_COLOR_PICKER 0
#define LV_USE_MSG_BOX 0
#define LV_USE_KEYBOARD 0

#define LV_USE_LAYOUT_FLEX 1
#define LV_USE_LAYOUT_GRID 1

#define LV_USE_FILESYSTEM 0
#define LV_USE_FS_POSIX 0
#define LV_USE_FS_FATFS 0
#define LV_USE_FS_SPIFFS 0

#define LV_USE_DEMO 0

#define LV_TICK_CUSTOM 1
#define LV_TICK_CUSTOM_INCLUDE "esp_timer.h"
#define LV_TICK_CUSTOM_SYS_TIME_EXPR (esp_timer_get_time() / 1000)

#define LV_USE_PERF_MONITOR 0

#define LV_USE_ASSERT_NULL 0
#define LV_USE_ASSERT_MALLOC 0
#define LV_USE_ASSERT_STYLE 0
#define LV_USE_ASSERT_MEM_INTEGRITY 0
#define LV_USE_ASSERT_OBJ 0

#define LV_USE_BIDI 0
#define LV_USE_UNICODE 1
#define LV_USE_BMP 0
#define LV_USE_GIF 0
#define LV_USE_JPG 0
#define LV_USE_PNG 0
#define LV_USE_TTF 0

#define LV_USE_RENDER_SW 1

#define LV_DISPLAY_DEF_REFR_PERIOD 30

#define LV_USE_LOG 0

#endif /* LV_CONF_H */